#!/usr/bin/env sh

set -e -u

read -r seconds < /proc/uptime
seconds="${seconds%%.*}"

if [ "$seconds" -ge 86400 ]; then # 60 * 60 * 24 = 86400
    days="$((seconds / 86400))"
    if [ "$days" -eq 1 ]; then
        days="${days} day"
    else
        days="${days} days"
    fi
fi

if [ "$seconds" -ge 3600 ]; then # 60 * 60 = 3600
    hours="$((seconds / 3600 % 24))"
    if [ "$hours" -eq 1 ]; then
        hours="${hours} hour"
    else
        hours="${hours} hours"
    fi
fi

if [ "$seconds" -ge 60 ]; then
    minutes="$((seconds / 60 % 60))"
    if [ "$minutes" -eq 1 ]; then
        minutes="${minutes} minute"
    else
        minutes="${minutes} minutes"
    fi
fi

uptime="${days:+"$days", }${hours:+"$hours", }${minutes:-}"
uptime="${uptime%, }"
uptime="${uptime:-"$seconds" seconds}"

printf '%s\n' "$uptime"
